FLASHCARD_BOOKMARK_TYPE = "0"
NOTE_BOOKMARK_TYPE = "1"
VIDEO_BOOKMARK_TYPE = "2"
BOOKMARK_TYPES = (
    (FLASHCARD_BOOKMARK_TYPE, "Flash Card"),
    (NOTE_BOOKMARK_TYPE, "Notes"),
    (VIDEO_BOOKMARK_TYPE, "Video"),
)

POST_UTME_FAQ_TYPE = "0"
APP_FAQ_TYPE = "1"
FAQ_TYPES = (
    (POST_UTME_FAQ_TYPE, "Post UTME"),
    (APP_FAQ_TYPE, "Platform"),
)

STUDY_GUIDE_TYPE = "0"
SSCE_GUIDE_TYPE = "1"
UTME_GUIDE_TYPE = "2"
POST_UTME_GUIDE_TYPE = "3"
GUIDE_TYPES = (
    (STUDY_GUIDE_TYPE, "Study Guide"),
    (SSCE_GUIDE_TYPE, "SSCE Guide"),
    (UTME_GUIDE_TYPE, "UTME Guide"),
    (POST_UTME_GUIDE_TYPE, "Post-UTME Guide"),
)

STUDY_MODE = "0"
EXAM_MODE = "1"
PLAN_MODES = (
    (STUDY_MODE, "Study mode"),
    (EXAM_MODE, "Exam mode"),
)

ONE_SIGNAL_PUSH_TOKEN_TYPE = "0"
FIREBASE_PUSH_TOKEN_TYPE = "1"
PUSH_TOKEN_TYPES = (
    (ONE_SIGNAL_PUSH_TOKEN_TYPE, "Onesignal"),
    (FIREBASE_PUSH_TOKEN_TYPE, "Firebase"),
)

SSCE_QUIZ_TYPE = "0"
CA_QUIZ_TYPE = "1"
UTME_QUIZ_TYPE = "2"
PUTME_QUIZ_TYPE = "3"
QUIZ_TYPES = (
    (SSCE_QUIZ_TYPE, "SSCE"),
    (CA_QUIZ_TYPE, "Current Affairs"),
    (UTME_QUIZ_TYPE, "UTME"),
    (PUTME_QUIZ_TYPE, "Post-UTME"),
)

OBJ_QUESTION_TYPE = "0"
THEORY_QUESTION_TYPE = "1"
QUESTION_TYPES = (
    (OBJ_QUESTION_TYPE, "Objective"),
    (THEORY_QUESTION_TYPE, "Theory"),
)
