# coding: utf-8

"""
    DocRaptor

    A native client library for the DocRaptor HTML to PDF/XLS service.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from docraptor.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class PrinceOptions(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    baseurl = StrSchema
    no_xinclude = BoolSchema
    no_network = BoolSchema
    no_parallel_downloads = BoolSchema
    http_user = StrSchema
    http_password = StrSchema
    http_proxy = StrSchema
    http_timeout = IntSchema
    insecure = BoolSchema
    media = StrSchema
    no_author_style = BoolSchema
    no_default_style = BoolSchema
    no_embed_fonts = BoolSchema
    no_subset_fonts = BoolSchema
    no_compress = BoolSchema
    encrypt = BoolSchema
    key_bits = IntSchema
    user_password = StrSchema
    owner_password = StrSchema
    disallow_print = BoolSchema
    disallow_copy = BoolSchema
    disallow_annotate = BoolSchema
    disallow_modify = BoolSchema
    debug = BoolSchema


    class input(
        _SchemaEnumMaker(
            enum_value_to_name={
                "html": "HTML",
                "xml": "XML",
                "auto": "AUTO",
            }
        ),
        StrSchema
    ):

        @classmethod
        @property
        def HTML(cls):
            return cls("html")

        @classmethod
        @property
        def XML(cls):
            return cls("xml")

        @classmethod
        @property
        def AUTO(cls):
            return cls("auto")
    version = StrSchema
    javascript = BoolSchema
    css_dpi = IntSchema
    profile = StrSchema
    pdf_title = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        baseurl: typing.Union[baseurl, Unset] = unset,
        no_xinclude: typing.Union[no_xinclude, Unset] = unset,
        no_network: typing.Union[no_network, Unset] = unset,
        no_parallel_downloads: typing.Union[no_parallel_downloads, Unset] = unset,
        http_user: typing.Union[http_user, Unset] = unset,
        http_password: typing.Union[http_password, Unset] = unset,
        http_proxy: typing.Union[http_proxy, Unset] = unset,
        http_timeout: typing.Union[http_timeout, Unset] = unset,
        insecure: typing.Union[insecure, Unset] = unset,
        media: typing.Union[media, Unset] = unset,
        no_author_style: typing.Union[no_author_style, Unset] = unset,
        no_default_style: typing.Union[no_default_style, Unset] = unset,
        no_embed_fonts: typing.Union[no_embed_fonts, Unset] = unset,
        no_subset_fonts: typing.Union[no_subset_fonts, Unset] = unset,
        no_compress: typing.Union[no_compress, Unset] = unset,
        encrypt: typing.Union[encrypt, Unset] = unset,
        key_bits: typing.Union[key_bits, Unset] = unset,
        user_password: typing.Union[user_password, Unset] = unset,
        owner_password: typing.Union[owner_password, Unset] = unset,
        disallow_print: typing.Union[disallow_print, Unset] = unset,
        disallow_copy: typing.Union[disallow_copy, Unset] = unset,
        disallow_annotate: typing.Union[disallow_annotate, Unset] = unset,
        disallow_modify: typing.Union[disallow_modify, Unset] = unset,
        debug: typing.Union[debug, Unset] = unset,
        input: typing.Union[input, Unset] = unset,
        version: typing.Union[version, Unset] = unset,
        javascript: typing.Union[javascript, Unset] = unset,
        css_dpi: typing.Union[css_dpi, Unset] = unset,
        profile: typing.Union[profile, Unset] = unset,
        pdf_title: typing.Union[pdf_title, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'PrinceOptions':
        return super().__new__(
            cls,
            *args,
            baseurl=baseurl,
            no_xinclude=no_xinclude,
            no_network=no_network,
            no_parallel_downloads=no_parallel_downloads,
            http_user=http_user,
            http_password=http_password,
            http_proxy=http_proxy,
            http_timeout=http_timeout,
            insecure=insecure,
            media=media,
            no_author_style=no_author_style,
            no_default_style=no_default_style,
            no_embed_fonts=no_embed_fonts,
            no_subset_fonts=no_subset_fonts,
            no_compress=no_compress,
            encrypt=encrypt,
            key_bits=key_bits,
            user_password=user_password,
            owner_password=owner_password,
            disallow_print=disallow_print,
            disallow_copy=disallow_copy,
            disallow_annotate=disallow_annotate,
            disallow_modify=disallow_modify,
            debug=debug,
            input=input,
            version=version,
            javascript=javascript,
            css_dpi=css_dpi,
            profile=profile,
            pdf_title=pdf_title,
            _configuration=_configuration,
            **kwargs,
        )
