"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import shared.shared_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TableAttributeDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    ATTRIBUTE_NAME_FIELD_NUMBER: builtins.int
    ATTRIBUTE_TYPE_FIELD_NUMBER: builtins.int
    @property
    def resource_info(self) -> shared.shared_pb2.ResourceInfo: ...
    attribute_name: builtins.str
    attribute_type: builtins.str
    def __init__(
        self,
        *,
        resource_info: shared.shared_pb2.ResourceInfo | None = ...,
        attribute_name: builtins.str = ...,
        attribute_type: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resource_info", b"resource_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["attribute_name", b"attribute_name", "attribute_type", b"attribute_type", "resource_info", b"resource_info"]) -> None: ...

global___TableAttributeDefinition = TableAttributeDefinition

@typing_extensions.final
class TableKeySchema(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    ATTRIBUTE_NAME_FIELD_NUMBER: builtins.int
    KEY_TYPE_FIELD_NUMBER: builtins.int
    @property
    def resource_info(self) -> shared.shared_pb2.ResourceInfo: ...
    attribute_name: builtins.str
    key_type: builtins.str
    def __init__(
        self,
        *,
        resource_info: shared.shared_pb2.ResourceInfo | None = ...,
        attribute_name: builtins.str = ...,
        key_type: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resource_info", b"resource_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["attribute_name", b"attribute_name", "key_type", b"key_type", "resource_info", b"resource_info"]) -> None: ...

global___TableKeySchema = TableKeySchema

@typing_extensions.final
class TableProjection(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    NON_KEY_ATTRIBUTES_FIELD_NUMBER: builtins.int
    PROJECTION_TYPE_FIELD_NUMBER: builtins.int
    @property
    def resource_info(self) -> shared.shared_pb2.ResourceInfo: ...
    @property
    def non_key_attributes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    projection_type: builtins.str
    def __init__(
        self,
        *,
        resource_info: shared.shared_pb2.ResourceInfo | None = ...,
        non_key_attributes: collections.abc.Iterable[builtins.str] | None = ...,
        projection_type: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resource_info", b"resource_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["non_key_attributes", b"non_key_attributes", "projection_type", b"projection_type", "resource_info", b"resource_info"]) -> None: ...

global___TableProjection = TableProjection

@typing_extensions.final
class TableProvisionedThroughput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    READ_CAPACITY_UNITS_FIELD_NUMBER: builtins.int
    WRITE_CAPACITY_UNITS_FIELD_NUMBER: builtins.int
    @property
    def resource_info(self) -> shared.shared_pb2.ResourceInfo: ...
    read_capacity_units: builtins.int
    write_capacity_units: builtins.int
    def __init__(
        self,
        *,
        resource_info: shared.shared_pb2.ResourceInfo | None = ...,
        read_capacity_units: builtins.int = ...,
        write_capacity_units: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resource_info", b"resource_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["read_capacity_units", b"read_capacity_units", "resource_info", b"resource_info", "write_capacity_units", b"write_capacity_units"]) -> None: ...

global___TableProvisionedThroughput = TableProvisionedThroughput

@typing_extensions.final
class TableGlobalSecondaryIndex(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    INDEX_NAME_FIELD_NUMBER: builtins.int
    KEY_SCHEMA_FIELD_NUMBER: builtins.int
    PROJECTION_FIELD_NUMBER: builtins.int
    PROVISIONED_THROUGHPUT_FIELD_NUMBER: builtins.int
    @property
    def resource_info(self) -> shared.shared_pb2.ResourceInfo: ...
    index_name: builtins.str
    @property
    def key_schema(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TableKeySchema]: ...
    @property
    def projection(self) -> global___TableProjection: ...
    @property
    def provisioned_throughput(self) -> global___TableProvisionedThroughput: ...
    def __init__(
        self,
        *,
        resource_info: shared.shared_pb2.ResourceInfo | None = ...,
        index_name: builtins.str = ...,
        key_schema: collections.abc.Iterable[global___TableKeySchema] | None = ...,
        projection: global___TableProjection | None = ...,
        provisioned_throughput: global___TableProvisionedThroughput | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["projection", b"projection", "provisioned_throughput", b"provisioned_throughput", "resource_info", b"resource_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["index_name", b"index_name", "key_schema", b"key_schema", "projection", b"projection", "provisioned_throughput", b"provisioned_throughput", "resource_info", b"resource_info"]) -> None: ...

global___TableGlobalSecondaryIndex = TableGlobalSecondaryIndex

@typing_extensions.final
class TableLocalSecondaryIndex(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    INDEX_NAME_FIELD_NUMBER: builtins.int
    KEY_SCHEMA_FIELD_NUMBER: builtins.int
    PROJECTION_FIELD_NUMBER: builtins.int
    @property
    def resource_info(self) -> shared.shared_pb2.ResourceInfo: ...
    index_name: builtins.str
    @property
    def key_schema(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TableKeySchema]: ...
    @property
    def projection(self) -> global___TableProjection: ...
    def __init__(
        self,
        *,
        resource_info: shared.shared_pb2.ResourceInfo | None = ...,
        index_name: builtins.str = ...,
        key_schema: collections.abc.Iterable[global___TableKeySchema] | None = ...,
        projection: global___TableProjection | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["projection", b"projection", "resource_info", b"resource_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["index_name", b"index_name", "key_schema", b"key_schema", "projection", b"projection", "resource_info", b"resource_info"]) -> None: ...

global___TableLocalSecondaryIndex = TableLocalSecondaryIndex

@typing_extensions.final
class TablePointInTimeRecoverySpecification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    POINT_IN_TIME_RECOVERY_ENABLED_FIELD_NUMBER: builtins.int
    @property
    def resource_info(self) -> shared.shared_pb2.ResourceInfo: ...
    point_in_time_recovery_enabled: builtins.bool
    def __init__(
        self,
        *,
        resource_info: shared.shared_pb2.ResourceInfo | None = ...,
        point_in_time_recovery_enabled: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resource_info", b"resource_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["point_in_time_recovery_enabled", b"point_in_time_recovery_enabled", "resource_info", b"resource_info"]) -> None: ...

global___TablePointInTimeRecoverySpecification = TablePointInTimeRecoverySpecification

@typing_extensions.final
class TableSSESpecification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    KMS_MASTER_KEY_ID_FIELD_NUMBER: builtins.int
    SSE_ENABLED_FIELD_NUMBER: builtins.int
    SSE_TYPE_FIELD_NUMBER: builtins.int
    @property
    def resource_info(self) -> shared.shared_pb2.ResourceInfo: ...
    kms_master_key_id: builtins.str
    sse_enabled: builtins.bool
    sse_type: builtins.str
    def __init__(
        self,
        *,
        resource_info: shared.shared_pb2.ResourceInfo | None = ...,
        kms_master_key_id: builtins.str = ...,
        sse_enabled: builtins.bool = ...,
        sse_type: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resource_info", b"resource_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["kms_master_key_id", b"kms_master_key_id", "resource_info", b"resource_info", "sse_enabled", b"sse_enabled", "sse_type", b"sse_type"]) -> None: ...

global___TableSSESpecification = TableSSESpecification

@typing_extensions.final
class TableStreamSpecification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    STREAM_VIEW_TYPE_FIELD_NUMBER: builtins.int
    @property
    def resource_info(self) -> shared.shared_pb2.ResourceInfo: ...
    stream_view_type: builtins.str
    def __init__(
        self,
        *,
        resource_info: shared.shared_pb2.ResourceInfo | None = ...,
        stream_view_type: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resource_info", b"resource_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["resource_info", b"resource_info", "stream_view_type", b"stream_view_type"]) -> None: ...

global___TableStreamSpecification = TableStreamSpecification

@typing_extensions.final
class TableTimeToLiveSpecification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    ATTRIBUTE_NAME_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    @property
    def resource_info(self) -> shared.shared_pb2.ResourceInfo: ...
    attribute_name: builtins.str
    enabled: builtins.bool
    def __init__(
        self,
        *,
        resource_info: shared.shared_pb2.ResourceInfo | None = ...,
        attribute_name: builtins.str = ...,
        enabled: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resource_info", b"resource_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["attribute_name", b"attribute_name", "enabled", b"enabled", "resource_info", b"resource_info"]) -> None: ...

global___TableTimeToLiveSpecification = TableTimeToLiveSpecification

@typing_extensions.final
class Table(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    ATTRIBUTE_DEFINITIONS_FIELD_NUMBER: builtins.int
    BILLING_MODE_FIELD_NUMBER: builtins.int
    GLOBAL_SECONDARY_INDEXES_FIELD_NUMBER: builtins.int
    KEY_SCHEMA_FIELD_NUMBER: builtins.int
    LOCAL_SECONDARY_INDEXES_FIELD_NUMBER: builtins.int
    POINT_IN_TIME_RECOVERY_SPECIFICATION_FIELD_NUMBER: builtins.int
    PROVISIONED_THROUGHPUT_FIELD_NUMBER: builtins.int
    SSE_SPECIFICATION_FIELD_NUMBER: builtins.int
    STREAM_SPECIFICATION_FIELD_NUMBER: builtins.int
    TABLE_NAME_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    TIME_TO_LIVE_SPECIFICATION_FIELD_NUMBER: builtins.int
    DELETION_PROTECTION_ENABLED_FIELD_NUMBER: builtins.int
    @property
    def resource_info(self) -> shared.shared_pb2.ResourceInfo: ...
    @property
    def attribute_definitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TableAttributeDefinition]: ...
    billing_mode: builtins.str
    @property
    def global_secondary_indexes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TableGlobalSecondaryIndex]: ...
    @property
    def key_schema(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TableKeySchema]: ...
    @property
    def local_secondary_indexes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TableLocalSecondaryIndex]: ...
    @property
    def point_in_time_recovery_specification(self) -> global___TablePointInTimeRecoverySpecification: ...
    @property
    def provisioned_throughput(self) -> global___TableProvisionedThroughput: ...
    @property
    def sse_specification(self) -> global___TableSSESpecification: ...
    @property
    def stream_specification(self) -> global___TableStreamSpecification: ...
    table_name: builtins.str
    @property
    def tags(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def time_to_live_specification(self) -> global___TableTimeToLiveSpecification: ...
    deletion_protection_enabled: builtins.bool
    def __init__(
        self,
        *,
        resource_info: shared.shared_pb2.ResourceInfo | None = ...,
        attribute_definitions: collections.abc.Iterable[global___TableAttributeDefinition] | None = ...,
        billing_mode: builtins.str = ...,
        global_secondary_indexes: collections.abc.Iterable[global___TableGlobalSecondaryIndex] | None = ...,
        key_schema: collections.abc.Iterable[global___TableKeySchema] | None = ...,
        local_secondary_indexes: collections.abc.Iterable[global___TableLocalSecondaryIndex] | None = ...,
        point_in_time_recovery_specification: global___TablePointInTimeRecoverySpecification | None = ...,
        provisioned_throughput: global___TableProvisionedThroughput | None = ...,
        sse_specification: global___TableSSESpecification | None = ...,
        stream_specification: global___TableStreamSpecification | None = ...,
        table_name: builtins.str = ...,
        tags: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        time_to_live_specification: global___TableTimeToLiveSpecification | None = ...,
        deletion_protection_enabled: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["point_in_time_recovery_specification", b"point_in_time_recovery_specification", "provisioned_throughput", b"provisioned_throughput", "resource_info", b"resource_info", "sse_specification", b"sse_specification", "stream_specification", b"stream_specification", "time_to_live_specification", b"time_to_live_specification"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["attribute_definitions", b"attribute_definitions", "billing_mode", b"billing_mode", "deletion_protection_enabled", b"deletion_protection_enabled", "global_secondary_indexes", b"global_secondary_indexes", "key_schema", b"key_schema", "local_secondary_indexes", b"local_secondary_indexes", "point_in_time_recovery_specification", b"point_in_time_recovery_specification", "provisioned_throughput", b"provisioned_throughput", "resource_info", b"resource_info", "sse_specification", b"sse_specification", "stream_specification", b"stream_specification", "table_name", b"table_name", "tags", b"tags", "time_to_live_specification", b"time_to_live_specification"]) -> None: ...

global___Table = Table

@typing_extensions.final
class DynamoDB_Table(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TABLE_FIELD_NUMBER: builtins.int
    @property
    def table(self) -> global___Table: ...
    def __init__(
        self,
        *,
        table: global___Table | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["table", b"table"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["table", b"table"]) -> None: ...

global___DynamoDB_Table = DynamoDB_Table
