from enum import Enum

class TemplateCategory(Enum):

    ACCOUNT_UPDATE = 'ACCOUNT_UPDATE'
    PAYMENT_UPDATE = 'PAYMENT_UPDATE'
    PERSONAL_FINANCE_UPDATE = 'PERSONAL_FINANCE_UPDATE'
    SHIPPING_UPDATE = 'SHIPPING_UPDATE'
    RESERVATION_UPDATE = 'RESERVATION_UPDATE'
    ISSUE_RESOLUTION = 'ISSUE_RESOLUTION'
    APPOINTMENT_UPDATE = 'APPOINTMENT_UPDATE'
    TRANSPORTATION_UPDATE = 'TRANSPORTATION_UPDATE'
    TICKET_UPDATE = 'TICKET_UPDATE'
    ALERT_UPDATE = 'ALERT_UPDATE'
    AUTO_REPLY = 'AUTO_REPLY'