
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-29T14:44:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7fd66d2bb371a46538334db6617490d00c0cf59",
 "version": "1.14.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
