MAX_ORDER_COUNT_IN_BASKET = 10
BRANDS_LOG_LIMIT = 5
PAREKENDE_SATIS_FISI_LIMIT = 10000.0
TYPE_NOT_CREATED = "NOTCREATED"
TYPE_CREATED = "CREATED"
REAL_ORDER = "0"
FAKE_ORDER = "1"
MAX_CONFIG_ATTEMPT_COUNT = 10
MAX_METADATA_ATTEMPT_COUNT = 10
PRODUCT_CODE = 10000
THRESHOLD_TIME_OTP = 90
GETIR_SCHEDULED_BEFORE_ORDER_HOUR = 58
THRESHOLD_DISTANCE_VALUE = 200
SEARCH_LIMIT_RECORD = 5
TOLERANCE_PAYMENT = 0.50
PAYMENT_PER_BASKET = 3.0
DYNAMO_DB_NULL_INDEX = 'N'
BASKET_STATUS_SHELF = "SHELF"
BASKET_STATUS_ON_THE_WAY = "ONTHEWAY"
lower_map = {
    ord("I"): "ı",
    ord("İ"): "i",
    ord("Ü"): "ü",
    ord("Ç"): "ç",
    ord("Ş"): "ş",
    ord("Ö"): "ö",
    ord("Ğ"): "ğ"
}

