
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-25T17:02:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6eaa14548a7b26a8ccc5eb139f694383eda35b5",
 "version": "0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
