from typing_extensions import Self

class InfoRequest:
    @classmethod
    def FromString(cls, s: str) -> Self: ...
    @classmethod
    def SerializeToString(cls, s: Self) -> str: ...
    ...

class JobRequest:
    working_dir: str
    files_name: str
    index: int
    @classmethod
    def FromString(cls, s: str) -> Self: ...
    @classmethod
    def SerializeToString(cls, s: Self) -> str: ...
    ...

class JobResponse:
    status: str
    message: str
    @classmethod
    def FromString(cls, s: str) -> Self: ...
    @classmethod
    def SerializeToString(cls, s: Self) -> str: ...
    ...

class Contact:
    name: str
    email: str
    @classmethod
    def FromString(cls, s: str) -> Self: ...
    @classmethod
    def SerializeToString(cls, s: Self) -> str: ...
    ...

class License:
    name: str
    url: str
    @classmethod
    def FromString(cls, s: str) -> Self: ...
    @classmethod
    def SerializeToString(cls, s: Self) -> str: ...
    ...

class InfoResponse:
    title: str
    description: str
    version: str
    contact: Contact
    license: License
    @classmethod
    def FromString(cls, s: str) -> Self: ...
    @classmethod
    def SerializeToString(cls, s: Self) -> str: ...
    ...
