VERSION_YEAR = 2023
VERSION_MONTH = int('09')
VERSION_DAY = int('28')
VERSION_HOUR = int('00')
VERSION_MINUTE = int('10')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202309280010
version_date = '2023/09/28 00:10'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
