import numpy as np
import numpy.linalg as npl
from .pinocchio_pywrap.rpy import matrixToRpy as matrixToRpy, rotate as rotate, rpyToMatrix as rpyToMatrix

def npToTTuple(M): ...
def npToTuple(M): ...
def eye(n): ...
def zero(n): ...
def rand(n): ...
def cross(a, b): ...
def skew(p): ...
def se3ToXYZQUAT(M): ...
def XYZQUATToSe3(vec): ...
def isapprox(a, b, epsilon: float = ...): ...
def mprint(M, name: str = ..., eps: float = ...): ...
def fromListToVectorOfString(items): ...
