VERSION_YEAR = 2023
VERSION_MONTH = int('09')
VERSION_DAY = int('28')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('24')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202309281624
version_date = '2023/09/28 16:24'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
