
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-29T09:38:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "67e1d36809b6aad3109d68203c2b92bf251ee756",
 "version": "0.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
