from . import BaseVisualizer
from _typeshed import Incomplete

class MeshcatVisualizer(BaseVisualizer):
    FORCE_SCALE: float
    FRAME_VEL_COLOR: int
    CAMERA_PRESETS: Incomplete
    def getViewerNodeName(self, geometry_object, geometry_type): ...
    viewer: Incomplete
    static_objects: Incomplete
    def initViewer(self, viewer: Incomplete | None = ..., open: bool = ..., loadModel: bool = ...) -> None: ...
    def setBackgroundColor(self, preset_name: str = ...) -> None: ...
    def setCameraTarget(self, target) -> None: ...
    def setCameraPosition(self, position) -> None: ...
    def setCameraPreset(self, preset_key) -> None: ...
    def setCameraZoom(self, zoom) -> None: ...
    def setCameraPose(self, pose=...) -> None: ...
    def disableCameraControl(self) -> None: ...
    def enableCameraControl(self) -> None: ...
    def loadMesh(self, geometry_object): ...
    def loadViewerGeometryObject(self, geometry_object, geometry_type, color: Incomplete | None = ...) -> None: ...
    viewerRootNodeName: Incomplete
    viewerCollisionGroupName: Incomplete
    viewerVisualGroupName: Incomplete
    def loadViewerModel(self, rootNodeName: str = ..., color: Incomplete | None = ...) -> None: ...
    def reload(self, new_geometry_object, geometry_type: Incomplete | None = ...) -> None: ...
    def clean(self) -> None: ...
    def delete(self, geometry_object, geometry_type) -> None: ...
    def display(self, q: Incomplete | None = ...) -> None: ...
    def updatePlacements(self, geometry_type) -> None: ...
    def addGeometryObject(self, obj, color: Incomplete | None = ...) -> None: ...
    def captureImage(self, w: Incomplete | None = ..., h: Incomplete | None = ...): ...
    display_collisions: bool
    def displayCollisions(self, visibility) -> None: ...
    display_visuals: bool
    def displayVisuals(self, visibility) -> None: ...
    def drawFrameVelocities(self, frame_id, v_scale: float = ..., color=...) -> None: ...
