{
 "title": "Onion Services",
 "description": "Onion Services status",
 "tags": [
  "tor",
  "onion services"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sites monitored",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_probe_status_info)"
    }
   ]
  },
  {
   "title": "Unreachable instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_descriptor_reachable == 0)"
    }
   ]
  },
  {
   "title": "Unreachable descriptors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_descriptor_reachable == 0)"
    }
   ]
  },
  {
   "title": "Invalid certificates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_valid_certificate == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid status codes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_unexpected_status_code == 1)"
    }
   ]
  },
  {
   "title": "Onion Services Latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "onion_service_descriptor_latency_seconds"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Number of introduction points",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "onion_service_introduction_points_number"
    }
   ]
  }
 ]
}