data = {
    "DOWNTOWN RISE": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [11, 50, 61, 76, 83, 86],
        "DPAD_RIGHT": [16, 34, 64],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "市中心高架桥",
    },
    "THE CITY BY THE BAY": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [31],
        "DPAD_RIGHT": [8, 33, 69, 81, 85],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "临湾城市",
    },
    "UPTOWN": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [41, 42, 66, 67],
        "DPAD_RIGHT": [6, 7, 8, 25, 26, 44, 45, 69, 70, 80, 81, 84, 85, 86, 90, 91],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "住宅区",
    },
    "DIPPING DOWN": {
        "DPAD_LEFT_DPAD_LEFT": [42],
        "DPAD_LEFT": [45, 52, 89],
        "DPAD_RIGHT": [4, 19, 36, 65, 68, 73, 92],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "坠落",
    },
    "LEAPS & BOUNDS": {
        "DPAD_LEFT_DPAD_LEFT": [59],
        "DPAD_LEFT": [63, 79, 90],
        "DPAD_RIGHT": [],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "急速飞跃",
    },
    "TIBER STREAM": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [1, 5, 6, 9, 11, 12, 31, 32, 42, 43, 67, 77, 78, 95, 96],
        "DPAD_RIGHT": [3, 14, 15, 26, 27, 56, 61, 65, 73, 73, 90],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "台伯河激流",
    },
    "THE CITY THAT NEVER SLEEPS": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [5, 6, 7, 11, 12, 31, 32, 49, 50, 60, 61, 66, 67],
        "DPAD_RIGHT": [2, 3, 18, 19, 44, 46, 78, 82, 83],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "不夜城",
    },
    "THE PEARL OF THE ORIENT": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [5, 6, 13, 26, 30, 63, 64, 76, 77, 87],
        "DPAD_RIGHT": [40, 41, 44, 45, 57, 60],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "东方明珠",
    },
    "CAVE HEAT": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [18, 19, 31, 37, 53, 54],
        "DPAD_RIGHT": [9, 10, 26, 27, 34, 35],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "洞穴热浪",
    },
    "MOUNTAIN POLES": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [15, 16, 41, 42, 43, 57, 58, 82, 88],
        "DPAD_RIGHT": [26, 31, 44, 45, 75, 76],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "山巅",
    },
    "QUANTUM JUMPS": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [15, 22, 52, 85],
        "DPAD_RIGHT": [18, 26, 38, 62, 65, 79],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "量子跃迁",
    },
    "ROLLER": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [3, 53, 66, 82],
        "DPAD_RIGHT": [19, 46, 56],
        "DPAD_RIGHT_DPAD_RIGHT": [23],
        "trackcn": "云霄飞车",
    },
    "URBAN BLAZE": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [51, 55, 68, 88],
        "DPAD_RIGHT": [2, 9, 28, 33, 83],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "城市烈焰",
    },
    "WHIRLWIND": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [4, 8, 79],
        "DPAD_RIGHT": [18, 41, 68, 85, 92],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "旋风弯道",
    },
    "SHEN CITY": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [5, 26, 50, 85],
        "DPAD_RIGHT": [16, 22, 44, 67, 90],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "申城",
    },
    "THE ETERNAL CITY": {
        "DPAD_LEFT_DPAD_LEFT": [71],
        "DPAD_LEFT": [0, 17, 64, 77, 82],
        "DPAD_RIGHT": [3, 21, 34, 44, 50, 57, 92],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "永恒之城",
    },
    "ANCIENT RUINS": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [33, 40, 71, 87],
        "DPAD_RIGHT": [1, 4, 15, 30, 51, 56, 67],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "古代遗迹",
    },
    "CLIFFHANGER": {
        "DPAD_LEFT_DPAD_LEFT": [56],
        "DPAD_LEFT": [20, 24, 37, 44, 53, 60, 63],
        "DPAD_RIGHT": [13, 76],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "悬崖峭壁",
    },
    "PANTHEON SPLIT": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [0, 2, 14, 42, 58, 70, 81],
        "DPAD_RIGHT": [10, 32],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "万神殿岔路",
    },
    "STARTING GRID": {
        "DPAD_LEFT_DPAD_LEFT": [],
        "DPAD_LEFT": [4, 8, 13, 58, 67, 89],
        "DPAD_RIGHT": [26, 75, 93],
        "DPAD_RIGHT_DPAD_RIGHT": [],
        "trackcn": "起跑排位",
    },
}
