from .abstract_parser import AbstractParser
from .jsonld import JSONLD
from .opengraph import OpenGraph
from .itemProp import ItemProp
from .metaProp import MetaProp
from .linkCanonicalProp import LinkCanonicalProp
from .titleTag import TitleTag
from .urlParser import URLParser
from .lastChanceParser import LastChanceParser
from .linkIcon import LinkIcon
