# Generated by Django 4.2.4 on 2023-09-12 00:44

import django.core.files.storage.filesystem
from django.db import migrations, models
import flashlearners_core.app.fields.media_field
import flashlearners_core.app.models.media
import flashlearners_core.app.models.notification
import flashlearners_core.app.models.quiz
import flashlearners_core.app.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_subject_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='media',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=flashlearners_core.app.fields.media_field.MediaField(default='', storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to=flashlearners_core.app.models.media.upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=flashlearners_core.app.fields.media_field.MediaField(storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to=flashlearners_core.app.models.notification.upload_to),
        ),
        migrations.AlterField(
            model_name='option',
            name='image',
            field=flashlearners_core.app.fields.media_field.MediaField(blank=True, null=True, storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to=flashlearners_core.app.models.quiz.upload_to2),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=flashlearners_core.app.fields.media_field.MediaField(blank=True, null=True, storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to=flashlearners_core.app.models.quiz.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=flashlearners_core.app.fields.media_field.MediaField(blank=True, null=True, storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to=flashlearners_core.app.models.user.upload_to),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
