# coding: utf-8

"""
    Oliver API

    Oliver API service  # noqa: E501

    OpenAPI spec version: 4.3.2
    Contact: api@behavioralsignals.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.behavioral_skill_id import BehavioralSkillId  # noqa: E501
from swagger_client.rest import ApiException


class TestBehavioralSkillId(unittest.TestCase):
    """BehavioralSkillId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBehavioralSkillId(self):
        """Test BehavioralSkillId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.behavioral_skill_id.BehavioralSkillId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
