VERSION_YEAR = 2023
VERSION_MONTH = int('09')
VERSION_DAY = int('29')
VERSION_HOUR = int('00')
VERSION_MINUTE = int('51')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202309290051
version_date = '2023/09/29 00:51'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
