from _typeshed import Incomplete
from typing import Union

fd: Incomplete
flags_save: Incomplete
attrs_save: Incomplete

def get(keycount: int = ..., bytes: bool = ...) -> Union[str, bytes]: ...
def getnum(keycount: int = ..., ints: bool = ...) -> Union[str, int]: ...
def getchars(
    keycount: int = ..., chars: list = ..., bytes: bool = ...
) -> Union[str, bytes]: ...
