def applyConfiguration(gui, name, tf) -> None: ...
def displayShape(gui, name, geom, color=...): ...
def displayDistanceResult(gui, group_name, res, closest_points: bool = ..., normal: bool = ...) -> None: ...
def displayCollisionResult(gui, group_name, res, color=...) -> None: ...
