STATE_ABBREVIATIONS = {
    'AL': 'Ala.',
    'AK': 'Alaska',
    'AZ': 'Ariz.',
    'AR': 'Ark.',
    'CA': 'Calif.',
    'CO': 'Colo.',
    'CT': 'Conn.',
    'DE': 'Del.',
    'FL': 'Fla.',
    'GA': 'Ga.',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Ill.',
    'IN': 'Ind.',
    'IA': 'Iowa',
    'KS': 'Kan.',
    'KY': 'Ky.',
    'LA': 'La.',
    'ME': 'Maine',
    'MD': 'Md.',
    'MA': 'Mass.',
    'MI': 'Mich.',
    'MN': 'Minn.',
    'MS': 'Miss.',
    'MO': 'Mo.',
    'MT': 'Mont.',
    'NE': 'Neb.',
    'NV': 'Nev.',
    'NH': 'N.H.',
    'NJ': 'N.J.',
    'NM': 'N.M.',
    'NY': 'N.Y.',
    'NC': 'N.C.',
    'ND': 'N.D.',
    'OH': 'Ohio',
    'OK': 'Okla.',
    'OR': 'Ore.',
    'PA': 'Pa.',
    'RI': 'R.I.',
    'SC': 'S.C.',
    'SD': 'S.D.',
    'TN': 'Tenn.',
    'TX': 'Tex.',
    'UT': 'Utah',
    'VT': 'Vt.',
    'VA': 'Va.',
    'WA': 'Wash.',
    'WV': 'W.Va.',
    'WI': 'Wis.',
    'WY': 'Wyo.',
    'Alabama': 'Ala.',
    'Alaska': 'Alaska',
    'Arizona': 'Ariz.',
    'Arkansas': 'Ark.',
    'California': 'Calif.',
    'Colorado': 'Colo.',
    'Connecticut': 'Conn.',
    'Delaware': 'Del.',
    'Florida': 'Fla.',
    'Georgia': 'Ga.',
    'Hawaii': 'Hawaii',
    'Idaho': 'Idaho',
    'Illinois': 'Ill.',
    'Indiana': 'Ind.',
    'Iowa': 'Iowa',
    'Kansas': 'Kan.',
    'Kentucky': 'Ky.',
    'Louisiana': 'La.',
    'Maine': 'Maine',
    'Maryland': 'Md.',
    'Massachusetts': 'Mass.',
    'Michigan': 'Mich.',
    'Minnesota': 'Minn.',
    'Mississippi': 'Miss.',
    'Missouri': 'Mo.',
    'Montana': 'Mont.',
    'Nebraska': 'Neb.',
    'Nevada': 'Nev.',
    'New Hampshire': 'N.H.',
    'New Jersey': 'N.J.',
    'New Mexico': 'N.M.',
    'New York': 'N.Y.',
    'North Carolina': 'N.C.',
    'North Dakota': 'N.D.',
    'Ohio': 'Ohio',
    'Oklahoma': 'Okla.',
    'Oregon': 'Ore.',
    'Pennsylvania': 'Pa.',
    'Rhode Island': 'R.I.',
    'South Carolina': 'S.C.',
    'South Dakota': 'S.D.',
    'Tennessee': 'Tenn.',
    'Texas': 'Tex.',
    'Utah': 'Utah',
    'Vermont': 'Vt.',
    'Virginia': 'Va.',
    'Washington': 'Wash.',
    'West Virginia': 'W.Va.',
    'Wisconsin': 'Wis.',
    'Wyoming': 'Wyo.'
}
