# Generated by Django 4.2.4 on 2023-09-14 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import flashlearners_core.app.models.media
import flashlearners_core.app.models.notification
import flashlearners_core.app.models.quiz
import flashlearners_core.app.models.subject
import flashlearners_core.app.models.user
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_video_media_video_file_video_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='novelchapter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('0', 'General Practice'), ('1', 'SSCE'), ('2', 'Current Affairs'), ('3', 'UTME'), ('4', 'Post-UTME')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.ImageField(upload_to=flashlearners_core.app.models.notification.upload_to),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=flashlearners_core.app.models.quiz.upload_to),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(upload_to=flashlearners_core.app.models.subject.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=flashlearners_core.app.models.user.upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=flashlearners_core.app.models.media.upload_to),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('year', models.IntegerField(unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.session'),
        ),
    ]
