# Generated by Django 4.2.5 on 2023-09-14 14:18

from django.db import migrations, models
import flashlearners_core.app.models.feedback


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_option_image_remove_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=flashlearners_core.app.models.feedback.upload_to),
        ),
        migrations.AddField(
            model_name='feedback',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=flashlearners_core.app.models.feedback.upload_to2),
        ),
    ]
