# Generated by Django 4.2.5 on 2023-09-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='type',
            field=models.CharField(
                null=True, blank=True, choices=[('0','SSCE'),('1', 'Current Affairs'), ('2', 'UTME'), ('3', 'Post-UTME')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('0', 'SSCE'), ('1', 'Current Affairs'), ('2', 'UTME'), ('3', 'Post-UTME')], max_length=1),
        ),
    ]
