from typing import NoReturn

class EXCEPTION:
    class Error(Exception):
        def __init__(self, *args: object) -> None: ...
    class FileNotExists(Exception):
        def __init__(self, *args: object) -> None: ...
    class FunctionIsNotImplemented(Exception):
        def __init__(self, *args: object) -> None: ...
    class ToolIsMissing(Exception):
        def __init__(self, *args: object) -> None: ...
    class SitePackageNotExists(Exception):
        def __init__(self, *args: object) -> None: ...
    @staticmethod
    def get_python_version() -> str: ...
    @staticmethod
    def inform(info: str) -> None: ...
    @classmethod
    def warn(cls, info: str) -> None: ...
    @classmethod
    def fatal(cls, info: str, error_type_id: int = ...) -> NoReturn: ...
