# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Client Reimbursement",
    "version": "14.0.1.0.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "depends": [
        "ssi_financial_accounting",
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_total_mixin",
        "ssi_transaction_partner_mixin",
        "ssi_transaction_date_due_mixin",
        "ssi_product_line_account_mixin",
        "ssi_accounting_entry_mixin",
        "ssi_company_currency_mixin",
        "ssi_currency_mixin",
        "ssi_localdict_mixin",
        "ssi_m2o_configurator_mixin",
        "base_duration",
        "base_automation",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/res_group_data.xml",
        "security/ir.model.access.csv",
        "security/ir_rule_data.xml",
        "data/ir_sequence_data.xml",
        "data/sequence_template_data.xml",
        "data/policy_template_data.xml",
        "data/approval_template_data.xml",
        "data/ir_actions_server_data.xml",
        "data/base_automation_data.xml",
        "data/account_journal_data.xml",
        "views/client_reimbursement_type_views.xml",
        "views/client_reimbursement_views.xml",
    ],
    "demo": [
        # "demo/account_account_demo.xml",
        # "demo/account_journal_demo.xml",
        # "demo/hr_expense_type_demo.xml",
    ],
}
